# Database configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/autobuses_db?serverTimezone=UTC
spring.datasource.username=spring_user
spring.datasource.password=123321
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.format_sql=true
jwt.secret=GpkNDqKGYOVhfz//L3WOc43HnbQtuENKzIQhy5NZwWki8GjGpRXmCMivnw1UQrnSAjlaeWef2lFCGn9AO6IP7Q==
jwt.expiration=3600000
server.port=8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=asensio0111@gmail.com
spring.mail.password=ictt zqtc bzqc jhul
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
